### ISSUE TITLE
Abnormal request response

### ISSUE THREAD

**Issue by ys1231** [tanu360/Facebook-SSL-Pinning-Bypass#3]
![screenshot-20231222-115644](https://github.com/tanu360/Facebook-SSL-Pinning-Bypass/assets/22706022/45262448-790b-4c05-8d87-bfcc06701131)

**Comment by tanu360** [comment]
Restart App.

**Comment by ys1231** [comment]
I want to learn how Facebook SSL Pinning Bypass works

**Comment by ys1231** [comment]
Do you have any related materials or tutorials? Or what's the idea?

**Comment by ys1231** [comment]
resolved
